model_list:
  - model_name: rekrutyuk-main
    litellm_params:
      model: ollama_chat/qwen3.5:4b
      api_base: http://host.docker.internal:11434
  - model_name: rekrutyuk-small
    litellm_params:
      model: ollama_chat/qwen3.5:4b
      api_base: http://host.docker.internal:11434

general_settings:
  store_prompts_in_spend_logs: true